---
title: "My English Activity Log : MEAL"
author:
  - name: "Leheureux Lara" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---

* **September**

I started "Wallangues" at the beginning of the month to work my English. I also watched videos in English on YouTube and downloaded the "Lyrics Training" app which I find very funny to the point of not seeing the time go by. As for my lessons, I regularly work on the different subjects. 

* **October** 

My main activities in English for this month were my classes as well as the creation of my blog and first article. I also watched some videos, sometimes documentaries, in English and started the British series *Luther* during my free time. This is a police series that follows the story of John Luther, a policeman from the criminal section of London. 

* **November** 

To diversify my activities in English while continuing to work on my classes and blog, I started reading the first volume of the famous Harry Potter saga in English. I also continued to use Lyrics Training and watch videos and series according to my "desires" of the moment. I dropped out of my police series to watch something that is more related to the history of England that I am very attracted to. 

* **February**

During this month, I focused instead on my new courses with a little rest to avoid falling behind. However, I worked my English trough series but mainly documentaries. Their themes were: History, the planet and animals. These are topics that interest me and particularly affect me as evidenced by my portfolio topic for this blog. I also worked on my articles and advanced training of the blog.

* **March**

With a few episodes from time to time and break of a few months, I arrived at the end of my police series: *Luther*. It is a very captivating series that also pushes us to try to put ourselves in place of the different characters and to feel what they feel. It is easy to get carried away and not see the time go by when you look at this series. I think It is a good unrestrained police series in terms of the topic or the images shown. I also worked on my English course and others. 

* **April**

I mainly worked on my blog and my other biology courses in order to advance in my studies before the evaluation. However, I took advantage of my pauses to watch from time to time small documentaries such as, for example, *The story of God* with Morgan Freeman. This documentary, although not in my favourite themes, is still interesting and intriguing. I have nevertheless learned some things mainly at the cultural level and perception of things in the world and in time. 

